name: Scheduled Release with PR

on:
  workflow_dispatch

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check if v1.0 tag exists, create if not
      id: check_tag
      run: |
        # Comprobar si el tag v1.0 existe
        tag_exists=$(git tag --list "v1.0")
        
        if [[ -z "$tag_exists" ]]; then
          echo "Tag v1.0 does not exist, creating it now."
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Crear el tag v1.0
          git tag "v1.0"
          git push origin "v1.0"
        else
          echo "Tag v1.0 already exists."
        fi

    - name: Get the latest tag or set v1.0 if none exist
      id: get_latest_tag
      run: |
        # Obtener el último tag, si no existe, usamos v1.0
        latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.0")
        echo "latest_tag=${latest_tag}" >> $GITHUB_ENV
        echo "Latest tag is: $latest_tag"

    - name: Increment the version (start with v1.0 if no tag exists)
      id: increment_version
      run: |
        latest_version="${{ env.latest_tag }}"
        
        # Si no hay versión previa, empezamos con v1.0
        if [[ "$latest_version" == "v0.0" || "$latest_version" == "v1.0" ]]; then
          new_version="v2.0"  # Si el tag es v1.0, lo incrementamos a v2.0
        else
          # Extraemos la versión mayor (major) e incrementamos
          IFS='.' read -r major minor <<< "${latest_version#v}"
          
          # Aumentamos la versión mayor (major)
          new_major=$((major + 1))
          new_version="v${new_major}.0"
        fi
        
        # Guardamos la nueva versión
        echo "new_version=${new_version}" >> $GITHUB_ENV
        echo "New version calculated: $new_version"

    - name: Create a new tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        # Crear el nuevo tag con la versión incrementada
        git tag ${{ env.new_version }}
        git push origin ${{ env.new_version }}

  create-pull-request:
    runs-on: ubuntu-latest
    needs: create-release

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install GitHub CLI
      run: |
        sudo apt-get install gh

    - name: Authenticate GitHub CLI
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    - name: Create Pull Request from develop to main
      run: |
        gh pr create \
          --title "Release ${{ env.new_version }}" \
          --body "This pull request prepares the release of version ${{ env.new_version }}." \
          --base main \
          --head develop \
          --draft false
